module.exports = [
  {
    id: 'ollama-minimax-m3',
    label: '🚀 MiniMax M3 (rápido, visión)',
    name: 'MiniMax M3',
    provider: 'ollama',
    modelTag: 'minimax-m3',
    modes_supported: ['speed', 'quality'],
    default_mode: 'quality',
    max_bytes: 10 * 1024 * 1024,
    modes: {
      speed:   { options: { temperature: 0, num_predict: 1024, num_ctx: 4096  }, prompt: 'short' },
      quality: { options: { temperature: 0, num_predict: 4096, num_ctx: 16384 }, prompt: 'full'  },
    },
  },
  {
    id: 'ollama-gemma4-31b',
    label: '⚖️ Gemma 4 31B (balance, visión)',
    name: 'Gemma 4 31B',
    provider: 'ollama',
    modelTag: 'gemma4:31b',
    modes_supported: ['speed', 'quality'],
    default_mode: 'quality',
    max_bytes: 10 * 1024 * 1024,
    modes: {
      speed:   { options: { temperature: 0, num_predict: 1024, num_ctx: 8192  }, prompt: 'short' },
      quality: { options: { temperature: 0, num_predict: 8192, num_ctx: 32768 }, prompt: 'full'  },
    },
  },
  {
    id: 'ollama-qwen35-397b',
    label: '💎 Qwen3.5 397B (lento, máxima calidad, visión)',
    name: 'Qwen3.5 397B',
    provider: 'ollama',
    modelTag: 'qwen3.5:397b',
    modes_supported: ['speed', 'quality'],
    default_mode: 'quality',
    max_bytes: 10 * 1024 * 1024,
    modes: {
      speed:   { options: { temperature: 0, num_predict: 2048, num_ctx: 8192  }, prompt: 'short' },
      quality: { options: { temperature: 0, num_predict: 8192, num_ctx: 32768 }, prompt: 'full'  },
    },
  },
  {
    id: 'ocrspace-engine2',
    label: '⚡ OCR.space Engine 2 (rápido, OCR clásico)',
    name: 'OCR.space Engine 2',
    provider: 'ocrspace',
    engine: 2,
    language: 'spa',
    modes_supported: ['quality'],
    default_mode: 'quality',
  },
];
